Configuration:
  name: Default 
  Properties:
    Property:
      name: log-path
      value: "/media/sda1/logging/logs"
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: Console_Appender
          level: info
    Logger:
      - name: frc.robot.Robot
        level: debug
        AppenderRef:
          - ref: Console_Appender
            level: info

